{{- if  .Values.downloader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: "downloader"
    {{- include "scicat.labels" . | nindent 4 }}
  name: downloader
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: "downloader"
      {{- include "scicat.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: "downloader"
        {{- include "scicat.selectorLabels" . | nindent 8 }}
      namespace: scicat-dev
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - envFrom:
            - secretRef:
                name: downloader-config
                optional: false
          image: {{ .Values.downloader.image | default "scicatdownloader" | quote }}
          imagePullPolicy: Always
          name: downloader
          ports:
            - containerPort: 3000
              name: downloader
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: mlzregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end -}}