{{- if  .Values.downloader.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: downloader
  labels:
    {{- include "scicat.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Values.downloader.service.name }}
      port: {{ .Values.downloader.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    {{- include "scicat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "downloader"
  sessionAffinity: None
  type: {{ .Values.frontend.service.type }}

{{- end }}