{{- if .Values.landingpage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: landingpage
  labels:
    app.kubernetes.io/component: "landingpage"
    {{- include "scicat.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Values.landingpage.service.name }}
      port: {{ .Values.landingpage.service.port }}
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "scicat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "landingpage"
  sessionAffinity: None
  type: {{ .Values.landingpage.service.type }}

{{- end }}