{{- if  .Values.landingpage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: "landingpage"
    {{- include "scicat.labels" . | nindent 4 }}
  name: landingpage
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
      matchLabels:
        app.kubernetes.io/component: "landingpage"
        {{- include "scicat.selectorLabels" . | nindent 8 }}
  strategy:
      rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
      type: RollingUpdate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: "landingpage"
        {{- include "scicat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity: {}
      containers:
        - image: {{ .Values.landingpage.image | default "scicatlandingpage" | quote }}
          imagePullPolicy: Always
          name: landingpage
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/assets/config.json
              name: landingpageconfig
              readOnly: true
              subPath: landingpage.config.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: landingpageconfig
          secret:
            defaultMode: 420
            optional: true
            secretName: landingpage-conf

{{- end -}}