{{- if .Values.panoscapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: panoscapi
  labels:
    app.kubernetes.io/component: "panoscapi"
    {{- include "scicat.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Values.panoscapi.service.name }}
      port: {{ .Values.panoscapi.service.port }}
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "scicat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "panoscapi"
  sessionAffinity: None
  type: {{ .Values.panoscapi.service.type }}

{{- end }}